# Orthogroups
In this notebook, we'll take a look at the output of Orthofinder and identify the photorespiiration enzymes in our target species.

In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO
from collections import defaultdict
from os import listdir
from os.path import splitext
from tqdm import tqdm

In [17]:
run_date = '12Nov2025'

## Read in data
We'll strt by looking at the `Orthogroups.tsv` file. We also want to import the AT numbers for the Arabidopsis versions of the genes we're looking for.

In [2]:
orthogroups = pd.read_csv('/mnt/research/Walker_Lab_Research/Serena_project_data/selection-under-heat_data/orthofinder/03No2025_all_species_Orthogroups.tsv', sep='\t', low_memory=False)
orthogroups.head()

,Orthogroup,translated_Acoerulea_322_v3.1.cds_primaryTranscriptOnly,translated_Acomosus_321_v3.cds_primaryTranscriptOnly,translated_AgerardiHAP1_783_v1.1.cds_primaryTranscriptOnly,translated_AhypogaeaLine8_886_v1.3.cds_primaryTranscriptOnly,translated_Aoccidentale_449_v0.9.cds_primaryTranscriptOnly,translated_Atequilanavar_WebersBlueHAP1_790_v2.1.cds_primaryTranscriptOnly,translated_Athaliana_447_Araport11.cds_primaryTranscriptOnly,translated_BhybridumBhyb26_693_v2.1.cds_primaryTranscriptOnly,translated_Bplatyphylla_679_v1.1.cds_primaryTranscriptOnly,...,translated_Tlatifoliavar_2019_6_853_v1.1.cds_primaryTranscriptOnly,translated_Tplicata_572_v3.1.cds_primaryTranscriptOnly,translated_Tpratense_385_v2.cds_primaryTranscriptOnly,translated_Vcarteri_317_v2.1.cds_primaryTranscriptOnly,translated_Vdarrowii_700_v1.2.cds_primaryTranscriptOnly,translated_Vvinifera_457_v2.1.cds_primaryTranscriptOnly,translated_YaloifoliaYa24Inoko_839_v2.1.cds_primaryTranscriptOnly,translated_Zmays_833_Zm-B73-REFERENCE-NAM-5.0.55.cds_primaryTranscriptOnly,translated_prepended_CsubellipsoideaC169_227_v2.0.cds_primaryTranscriptOnly,translated_prepended_Smoellendorffii_91_v1.0.cds_primaryTranscriptOnly
0,OG0000000,Aqcoe0541s0001.1 pacid=33091768 polypeptide=Aq...,Aco000135.1 pacid=33042441 polypeptide=Aco0001...,AndgeH1.01AG001000.1 pacid=57338243 polypeptid...,AhLine8.01G009500.1 pacid=64827772 polypeptide...,Anaoc.0001s0502.1 pacid=37553830 polypeptide=A...,AgateH1.01G022100.1 pacid=57831208 polypeptide...,AT1G03510.1 pacid=37392137 polypeptide=AT1G035...,Bhyb26.D01G001400.1 pacid=51520616 polypeptide...,BPChr01G00548 pacid=50813750 polypeptide=BPChr...,...,Tylat.01G005300.1 pacid=62721257 polypeptide=T...,Thupl.28202865s0001.1 pacid=44979454 polypepti...,Tp57577_TGAC_v2_mRNA10243 pacid=35981621 polyp...,NaN,Vadar_g10031.t1 pacid=52046125 polypeptide=Vad...,VIT_200s0179g00220.1 pacid=38049603 polypeptid...,Yucal.01G023700.1 pacid=61526493 polypeptide=Y...,Zm00001eb002930_T001 pacid=61177711 polypeptid...,NaN,Smollendorffii100216 pacid=15420961 polypeptid...
1,OG0000001,Aqcoe0071s0002.1 pacid=33084633 polypeptide=Aq...,Aco000310.1 pacid=33042938 polypeptide=Aco0003...,AndgeH1.01AG103100.1 pacid=57338018 polypeptid...,AhLine8.02G175100.1 pacid=64840868 polypeptide...,Anaoc.0014s0200.1 pacid=37546849 polypeptide=A...,AgateH1.01G048500.1 pacid=57831587 polypeptide...,AT1G04625.1 pacid=37398494 polypeptide=AT1G046...,Bhyb26.D01G037800.1 pacid=51527689 polypeptide...,BPChr01G05174 pacid=50813934 polypeptide=BPChr...,...,NaN,Thupl.28170576s0001.1 pacid=44943991 polypepti...,Tp57577_TGAC_v2_mRNA10862 pacid=35968950 polyp...,NaN,Vadar_g10017.t1 pacid=52046259 polypeptide=Vad...,VIT_215s0021g00810.1 pacid=38040437 polypeptid...,Yucal.01G081800.1 pacid=61527213 polypeptide=Y...,Zm00001eb279530_T001 pacid=61192260 polypeptid...,NaN,NaN
2,OG0000002,Aqcoe0015s0006.1 pacid=33098367 polypeptide=Aq...,Aco002021.1 pacid=33044819 polypeptide=Aco0020...,AndgeH1.01BG234100.1 pacid=57383204 polypeptid...,AhLine8.03G125400.1 pacid=64814314 polypeptide...,Anaoc.0002s0364.1 pacid=37515686 polypeptide=A...,AgateH1.01G077900.1 pacid=57831467 polypeptide...,AT1G42190.1 pacid=37399316 polypeptide=AT1G421...,Bhyb26.D01G535300.1 pacid=51517475 polypeptide...,BPChr04G25220 pacid=50811092 polypeptide=BPChr...,...,Tylat.03G033000.1 pacid=62713494 polypeptide=T...,Thupl.28445139s0001.1 pacid=44951194 polypepti...,Tp57577_TGAC_v2_mRNA11600 pacid=35987994 polyp...,Vocar.0002s0375.1 pacid=32891029 polypeptide=V...,Vadar_g10197.t1 pacid=52044296 polypeptide=Vad...,VIT_200s0227g00030.1 pacid=38050389 polypeptid...,Yucal.01G218700.1 pacid=61530997 polypeptide=Y...,NaN,NaN,Smollendorffii136708 pacid=15419309 polypeptid...
3,OG0000003,Aqcoe5G049000.1 pacid=33086099 polypeptide=Aqc...,Aco021638.1 pacid=33040729 polypeptide=Aco0216...,AndgeH1.01AG074600.1 pacid=57341166 polypeptid...,AhLine8.01G039700.1 pacid=64825845 polypeptide...,Anaoc.0001s0947.1 pacid=37548454 polypeptide=A...,AgateH1.01G034900.1 pacid=57828485 polypeptide...,AT4G20220.1 pacid=37390155 polypeptide=AT4G202...,Bhyb26.D01G112000.1 pacid=51524265 polypeptide...,BPChr13G08943 pacid=50823494 polypeptide=BPChr...,...,Tylat.02G058800.1 pacid=62747039 polypeptide=T...,Thupl.28547116s0001.1 pacid=44981763 polypepti...,Tp57577_TGAC_v2_mRNA10136 pacid=35960015 polyp...,NaN,Vadar_g19553.t1 pacid=52039691 polypeptide=Vad...,VIT_203s0110g00150.1 pacid=38036082 polypeptid...,Yucal.01G079200.1 pacid=61531963 polypeptide=Y...,NaN,NaN,Smollendorffii138647 pacid=15402141 polypeptid...
4,OG0000004,Aqcoe1G124800.1 pacid=33084070 polypeptide=Aqc...,Aco006868.1 pacid=33045899 polypeptide=Aco0068...,AndgeH1.01AG180400.1 pacid=57338504 polypeptid...,AhLine8.02G005400.1 pacid=64842838 polypeptide...,Anaoc.0001s2319.1 pacid=37551873 polypeptide=A...,AgateH1.01G225100.1 pacid=57829407 polypeptide...,AT1G11280.1 pacid=37402911 polypeptide=AT1G112...,Bhyb26.D01G043100.1 pacid=51517315 polypeptide...,BPChr02G10550 pacid=50801314 polypeptide=BPChr...,...,Tylat.03G005400.1 pacid=62712858 polypeptide=T...,Thupl.28190514s0001.1 pacid=45003868 polypepti...,Tp57577_TGAC_v2_mRNA102 pacid=35952307 polypep...,NaN,Vadar_g12674.t1 pacid=52024557 polypeptide=Vad...,VIT_200s0203g00220.1 pacid=38048711 polypeptid...,Yucal.01G223200.1 pacid=61529878 polypeptide=Y...,Zm00001eb008940_T001 pacid=61173308 polypeptid...,NaN,Smollendorffii17623 pacid=15421442 polypeptide...

In [3]:
with open('/mnt/research/Walker_Lab_Research/Serena_project_data/selection-under-heat_data/sequences/photorespiration_gene_ids.txt') as f:
    photo_genes = [l.strip() for l in f.readlines()]
photo_genes = [g.upper() for g in photo_genes]
photo_genes

['AT5G36700',
 'AT3G14420',
 'AT4G35090',
 'AT1G23310',
 'AT1G70580',
 'AT4G33010',
 'AT2G35370',
 'AT1G11860',
 'AT1G48030',
 'AT4G37930',
 'AT2G13360',
 'AT1G68010',
 'AT1G80380']

## Finding orthogroups
The basic approach here is to find the orthogroups that have the Arabidopsis photorespiration genes. We'll need to do some manual work to confirm them, but as a first step, we can do this in an automated fashion:

In [4]:
# Get the full name of the Arabidopsis column
ara_col = orthogroups.columns[np.where(orthogroups.columns.str.contains('thaliana'))[0]][0]

In [5]:
idx_to_keep = []
for pg in photo_genes:
    contains_df = orthogroups[ara_col].str.contains(pg).dropna()
    idx_to_keep.extend(contains_df[contains_df].index.tolist())
photo_orthos = orthogroups.loc[idx_to_keep].reset_index(drop=True)
photo_orthos

,Orthogroup,translated_Acoerulea_322_v3.1.cds_primaryTranscriptOnly,translated_Acomosus_321_v3.cds_primaryTranscriptOnly,translated_AgerardiHAP1_783_v1.1.cds_primaryTranscriptOnly,translated_AhypogaeaLine8_886_v1.3.cds_primaryTranscriptOnly,translated_Aoccidentale_449_v0.9.cds_primaryTranscriptOnly,translated_Atequilanavar_WebersBlueHAP1_790_v2.1.cds_primaryTranscriptOnly,translated_Athaliana_447_Araport11.cds_primaryTranscriptOnly,translated_BhybridumBhyb26_693_v2.1.cds_primaryTranscriptOnly,translated_Bplatyphylla_679_v1.1.cds_primaryTranscriptOnly,...,translated_Tlatifoliavar_2019_6_853_v1.1.cds_primaryTranscriptOnly,translated_Tplicata_572_v3.1.cds_primaryTranscriptOnly,translated_Tpratense_385_v2.cds_primaryTranscriptOnly,translated_Vcarteri_317_v2.1.cds_primaryTranscriptOnly,translated_Vdarrowii_700_v1.2.cds_primaryTranscriptOnly,translated_Vvinifera_457_v2.1.cds_primaryTranscriptOnly,translated_YaloifoliaYa24Inoko_839_v2.1.cds_primaryTranscriptOnly,translated_Zmays_833_Zm-B73-REFERENCE-NAM-5.0.55.cds_primaryTranscriptOnly,translated_prepended_CsubellipsoideaC169_227_v2.0.cds_primaryTranscriptOnly,translated_prepended_Smoellendorffii_91_v1.0.cds_primaryTranscriptOnly
0,OG0002242,Aqcoe4G129900.1 pacid=33066520 polypeptide=Aqc...,Aco008063.1 pacid=33032299 polypeptide=Aco0080...,AndgeH1.01AG005500.1 pacid=57339218 polypeptid...,AhLine8.04G054000.1 pacid=64839077 polypeptide...,Anaoc.0005s0234.1 pacid=37525864 polypeptide=A...,AgateH1.01G302500.1 pacid=57830997 polypeptide...,AT5G36700.4 pacid=37416686 polypeptide=AT5G367...,Bhyb26.D02G387200.1 pacid=51529138 polypeptide...,BPChr05G14757 pacid=50814855 polypeptide=BPChr...,...,Tylat.09G061000.1 pacid=62733152 polypeptide=T...,Thupl.29379746s0003.1 pacid=44950181 polypepti...,Tp57577_TGAC_v2_mRNA18145 pacid=35961266 polyp...,Vocar.0001s1317.1 pacid=32885481 polypeptide=V...,Vadar_g1901.t1 pacid=52029797 polypeptide=Vada...,VIT_200s0194g00110.1 pacid=38048793 polypeptid...,Yucal.01G302600.1 pacid=61531861 polypeptide=Y...,Zm00001eb064870_T001 pacid=61179706 polypeptid...,Csubellipsoidea61099 pacid=27390732 polypeptid...,Smollendorffii417198 pacid=15401614 polypeptid...
1,OG0000625,Aqcoe1G188500.1 pacid=33077808 polypeptide=Aqc...,Aco005107.1 pacid=33048657 polypeptide=Aco0051...,AndgeH1.01AG054600.1 pacid=57337279 polypeptid...,AhLine8.03G369700.1 pacid=64814523 polypeptide...,Anaoc.0001s2009.1 pacid=37552984 polypeptide=A...,AgateH1.08G075200.1 pacid=57817264 polypeptide...,AT3G14130.1 pacid=37405630 polypeptide=AT3G141...,Bhyb26.D01G048900.1 pacid=51518554 polypeptide...,BPChr04G18347 pacid=50811041 polypeptide=BPChr...,...,Tylat.03G067500.1 pacid=62712103 polypeptide=T...,Thupl.29379579s0003.1 pacid=44979471 polypepti...,Tp57577_TGAC_v2_mRNA30783 pacid=35968999 polyp...,NaN,Vadar_g30372.t1 pacid=52041404 polypeptide=Vad...,VIT_209s0002g00810.7 pacid=38070406 polypeptid...,Yucal.08G073500.1 pacid=61472601 polypeptide=Y...,Zm00001eb070270_T004 pacid=61168717 polypeptid...,NaN,Smollendorffii266585 pacid=15409182 polypeptid...
2,OG0001411,Aqcoe5G121500.1 pacid=33087865 polypeptide=Aqc...,Aco010626.1 pacid=33049307 polypeptide=Aco0106...,AndgeH1.01BG477300.1 pacid=57379424 polypeptid...,AhLine8.08G018300.1 pacid=64830816 polypeptide...,Anaoc.0009s0162.1 pacid=37496986 polypeptide=A...,AgateH1.03G164600.1 pacid=57848818 polypeptide...,AT1G20620.6 pacid=37396564 polypeptide=AT1G206...,Bhyb26.D01G294800.1 pacid=51522680 polypeptide...,BPChr01G16920 pacid=50813365 polypeptide=BPChr...,...,Tylat.01G083900.1 pacid=62718035 polypeptide=T...,Thupl.29379422s0008.1 pacid=44965481 polypepti...,Tp57577_TGAC_v2_mRNA39406 pacid=35955901 polyp...,Vocar.0011s0197.1 pacid=32895313 polypeptide=V...,Vadar_g26040.t1 pacid=52032478 polypeptide=Vad...,VIT_200s0698g00010.2 pacid=38048593 polypeptid...,Yucal.03G162600.1 pacid=61509672 polypeptide=Y...,Zm00001eb002510_T002 pacid=61171381 polypeptid...,Csubellipsoidea15220 pacid=27386617 polypeptid...,Smollendorffii112333 pacid=15412583 polypeptid...
3,OG0003500,Aqcoe5G404100.1 pacid=33091242 polypeptide=Aqc...,Aco010546.1 pacid=33048680 polypeptide=Aco0105...,AndgeH1.02AG007100.1 pacid=57281657 polypeptid...,AhLine8.05G109100.1 pacid=64776987 polypeptide...,Anaoc.0002s0360.1 pacid=37513130 polypeptide=A...,AgateH1.08G150900.1 pacid=57817415 polypeptide...,AT1G23310.1 pacid=37400735 polypeptide=AT1G233...,Bhyb26.D01G590100.1 pacid=51519364 polypeptide...,BPChr08G25555 pacid=50820539 polypeptide=BPChr...,...,Tylat.03G019700.1 pacid=62715399 polypeptide=T...,Thupl.29380742s0004.1 pacid=44962498 polypepti...,Tp57577_TGAC_v2_mRNA40094 pacid=35965894 polyp...,Vocar.0028s0159.1 pacid=32895688 polypeptide=V...,Vadar_g13512.t1 pacid=52024436 polypeptide=Vad...,VIT_200s0225g00130.1 pacid=38047596 polypeptid...,Yucal.08G148200.1 pacid=61473068 polypeptide=Y...,Zm00001eb118240_T001 pacid=61162133 polypeptid...,Csubellipsoidea26706 pacid=27389355 polypeptid...,Smollendorffii145611 pacid=15422755 polypeptid...
4,OG0003500,Aqcoe5G404100.1 pacid=33091242 polypeptide=Aqc...,Aco010546.1 pacid=33048680 polypeptide=Aco0105...,AndgeH1.02AG007100.1 pacid=57281657 polypeptid...,AhLine8.05G109100.1 pacid=64776987 polypeptide...,Anaoc.0002s0360.1 pacid=37513130 polypeptide=A...,AgateH1.08G150900.1 pacid=57817415 polypeptide...,AT1G23310.1 pacid=37400735 polypeptide=AT1G233...,Bhyb26.D01G590100.1 pacid=51519364 polypeptide...,BPChr08G25555 pacid=50820539 polypeptide=BPChr...,...,Tylat.03G019700.1 pacid=62715399 polypeptide=T...,Thupl.29380742s0004.1 pacid=44962498 polypepti...,Tp57577_TGAC_v2_mRNA40094 pacid=35965894 polyp...,Vocar.0028s0159.1 pacid=32895688 polypeptide=V...,Vadar_g13512.t1 pacid=52024436 polypeptide=Vad...,VIT_200s0225g00130.1 pacid=38047596 polypeptid...,Yucal.08G148200.1 pacid=61473068 polypeptide=Y...,Zm00001eb118240_T001 pacid=61162133 polypeptid...,Csubellipsoidea26706 pacid=27389355 polypeptid...,Smollendorffii145611 pacid=15422755 polypeptid...
5,OG0002785,Aqcoe7G130300.1 pacid=33075997 polypeptide=Aqc...,Aco005874.1 pacid=33034765 polypeptide=Aco0058...,AndgeH1.08AG039500.1 pacid=57277168 polypeptid...,AhLine8.06G240500.1 pacid=64807652 polypeptide...,Anaoc.0013s0451.1 pacid=37542624 polypeptide=A...,AgateH1.05G026700.1 pacid=57836653 polypeptide...,AT2G26080.1 pacid=37377756 polypeptide=AT2G260...,Bhyb26.D02G460900.1 pacid=51529161 polypeptide...,BPChr12G11420 pacid=50808853 polypeptide=BPChr...,...,Tylat.05G179300.1 pacid=62746087 polypeptide=T...,Thupl.29377959s0003.1 pacid=44958733 polypepti...,Tp57577_TGAC_v2_mRNA13442 pacid=35980754 polyp...,Vocar.0034s0106.1 pacid=32893075 polypeptide=V...,Vadar_g42900.t1 pacid=52021509 polypeptide=Vad...,VIT_204s0008g01300.2 pacid=38068962 polypeptid...,Yucal.05G031900.1 pacid=61496874 polypeptide=Y...,Zm00001eb259850_T001 pacid=61193154 polypeptid...,Csubellipsoidea52793 pacid=27389710 polypeptid...,Smollendorffii153563 pacid=15423428 polypeptid...
6,OG0002029,Aqcoe1G166700.1 pacid=33083425 polypeptide=Aqc...,Aco008361.1 pacid=33052031 polypeptide=Aco0083...,AndgeH1.04AG052900.1 pacid=57304290 polypeptid...,AhLine8.04G108900.1 pacid=64839915 polypeptide...,Anaoc.0004s0776.1 pacid=37495585 polypeptide=A...,AgateH1.15G075600.1 pacid=57839827 polypeptide...,AT1G32470.1 pacid=37392114 polypeptide=AT1G324...,Bhyb26.D03G055500.1 pacid=51472397 polypeptide...,BPChr02G02304 pacid=50801086 polypeptide=BPChr...,...,Tylat.05G029800.1 pacid=62745983 polypeptide=T...,Thupl.29380017s0013.1 pacid=44972673 polypepti...,Tp57577_TGAC_v2_mRNA21713 pacid=35972694 polyp...,Vocar.0002s0665.1 pacid=32890944 polypeptide=V...,Vadar_g40859.t1 pacid=52035329 polypeptide=Vad...,VIT_201s0011g01990.2 pacid=38026464 polypeptid...,Yucal.13G009500.1 pacid=61504827 polypeptide=Y...,Zm00001eb025960_T001 pacid=61179944 polypeptid...,Csubellipsoidea17602 pacid=27391712 polypeptid...,Smollendorffii113331 pacid=15415537 polypeptid...
7,OG0004508,Aqcoe1G292600.1 pacid=33082195 polypeptide=Aqc...,Aco014842.1 pacid=33039383 polypeptide=Aco0148...,AndgeH1.06AG216300.1 pacid=57395422 polypeptid...,AhLine8.04G040700.1 pacid=64837111 polypeptide...,Anaoc.0007s1522.1 pacid=37511063 polypeptide=A...,AgateH1.13G012400.1 pacid=57874057 polypeptide...,AT1G11860.3 pacid=37394809 polypeptide=AT1G118...,Bhyb26.D05G200200.1 pacid=51496388 polypeptide...,BPChr07G22613 pacid=50817635 polypeptide=BPChr...,...,Tylat.09G076800.1 pacid=62732157 polypeptide=T...,Thupl.29380489s0007.1 pacid=44989880 polypepti...,Tp57577_TGAC_v2_mRNA38304 pacid=35972155 polyp...,Vocar.0035s0099.1 pacid=32896794 polypeptide=V...,Vadar_g40578.t1 pacid=52036740 polypeptide=Vad...,VIT_210s0116g01540.3 pacid=38054599 polypeptid...,Yucal.13G017300.1 pacid=61504303 polypeptide=Y...,Zm00001eb070250_T001 pacid=61167410 polypeptid...,Csubellipsoidea28888 pacid=27386826 polypeptid...,Smollendorffii272095 pacid=15423109 polypeptid...
8,OG0003288,Aqcoe2G261200.1 pacid=33059836 polypeptide=Aqc...,Aco007341.1 pacid=33047895 polypeptide=Aco0073...,AndgeH1.03AG145700.1 pacid=57363101 polypeptid...,AhLine8.01G196700.1 pacid=64825746 polypeptide...,Anaoc.0008s0055.1 pacid=37561309 polypeptide=A...,AgateH1.02G028600.1 pacid=57855638 polypeptide...,AT1G48030.3 pacid=37400013 polypeptide=AT1G480...,Bhyb26.D02G130000.1 pacid=51538112 polypeptide...,BPChr08G15784 pacid=50820104 polypeptide=BPChr...,...,Tylat.06G080900.1 pacid=62738379 polypeptide=T...,Thupl.29378807s0004.1 pacid=44950337 polypepti...,Tp57577_TGAC_v2_mRNA12933 pacid=35970921 polyp...,Vocar.0027s0029.1 pacid=32887084 polypeptide=V...,Vadar_g11578.t1 pacid=52023552 polypeptide=Vad...,VIT_205s0020g00380.1 pacid=38073607 polypeptid...,Yucal.01G265500.1 pacid=61527108 polypeptide=Y...,Zm00001eb131070_T001 pacid=61206814 polypeptid...,Csubellipsoidea67663 pacid=27394779 polypeptid...,Smollendorffii445122 pacid=15417233 polypeptid...
9,OG0002447,Aqcoe6G069100.1 pacid=33061848 polypeptide=Aqc...,Aco013317.1 pacid=33029875 polypeptide=Aco0133...,AndgeH1.01AG094900.1 pacid=57341281 polypeptid...,AhLine8.03G290200.1 pacid=64812968 polypeptide...,Anaoc.0001s1447.1 pacid=37550508 polypeptide=A...,AgateH1.03G063900.1 pacid=57848625 polypeptide...,AT4G37930.1 pacid=37387523 polypeptide=AT4G379...,Bhyb26.D01G079300.1 pacid=51517698 polypeptide...,BPChr01G22904 pacid=50812774 polypeptide=BPChr...,...,Tylat.04G146200.1 pacid=62757633 polypeptide=T...,Thupl.29378085s0011.1 pacid=44964279 polypepti...,Tp57577_TGAC_v2_mRNA27959 pacid=35963617 polyp...,Vocar.0041s0018.1 pacid=32888726 polypeptide=V...,Vadar_g20450.t1 pacid=52039141 polypeptide=Vad...,VIT_200s0211g00070.1 pacid=38049652 polypeptid...,Yucal.05G283600.1 pacid=61493697 polypeptide=Y...,Zm00001eb056550_T001 pacid=61177236 polypeptid...,Csubellipsoidea59654 pacid=27392918 polypeptid...,Smollendorffii270566 pacid=15421045 polypeptid...
10,OG0004623,Aqcoe2G034800.1 pacid=33056156 polypeptide=Aqc...,Aco003139.1 pacid=33040318 polypeptide=Aco0031...,AndgeH1.07AG214200.1 pacid=57335906 polypeptid...,AhLine8.07G040600.1 pacid=64823519 polypeptide...,Anaoc.0005s0645.1 pacid=37524008 polypeptide=A...,AgateH1.02G062700.1 pacid=57860071 polypeptide...,AT2G13360.1 pacid=37380363 polypeptide=AT2G133...,Bhyb26.D03G379000.1 pacid=51469249 polypeptide...,NaN,...,Tylat.01G270200.1 pacid=62718450 polypeptide=T...,Thupl.29381062s0001.1 pacid=44995775 polypepti...,Tp57577_TGAC_v2_mRNA20025 pacid=35968628 polyp...,Vocar.0001s0284.1 pacid=32885778 polypeptide=V...,Vadar_g39424.t1 pacid=52034922 polypeptide=Vad...,VIT_206s0009g03740.1 pacid=38061890 polypeptid...,Yucal.01G205500.1 pacid=61531953 polypeptide=Y...,Zm00001eb034260_T001 pacid=61170661 polypeptid...,Csubellipsoidea23313 pacid=27390910 polypeptid...,Smollendorffii228964 pacid=15411621 polypeptid...
11,OG0004391,Aqcoe6G218000.1 pacid=33062795 polypeptide=Aqc...,Aco010381.1 pacid=33031990 polypeptide=Aco0103...,AndgeH1.04AG002300.1 pacid=57304705 polypeptid...,AhLine8.09G207300.1 pacid=64779706 polypeptide...,Anaoc.0003s1317.1 pacid=37536743 polypeptide=A...,AgateH1.03G186200.1 pacid=57852534 polypeptide...,AT1G68010.2 pacid=37391965 polypeptide=AT1G680...,Bhyb26.D03G003000.1 pacid=51471297 polypeptide...,BPChr09G16335 pacid=50806518 polypeptide=BPChr...,...,Tylat.03G101900.1 pacid=62713368 polypeptide=T...,Thupl.29381493s0015.1 pacid=44952580 polypepti...,Tp57577_TGAC_v2_mRNA11522 pacid=35953659 polyp...,Vocar.0001s0228.1 pacid=32884691 polypeptide=V...,Vadar_g22050.t1 pacid=52038482 polypeptide=Vad...,VIT_203s0038g02510.1 pacid=38034905 polypeptid...,Yucal.03G186300.1 pacid=61509727 polypeptide=Y...,Zm00001eb229250_T001 pacid=61204850 polypeptid...,Csubellipsoidea23324 pacid=27391281 polypeptid...,Smollendorffii271022 pacid=15420121 polypeptid...
12,OG0004763,Aqcoe7G397700.1 pacid=33073630 polypeptide=Aqc...,Aco017142.1 pacid=33032535 polypeptide=Aco0171...,AndgeH1.03AG239900.1 pacid=57361672 polypeptid...,AhLine8.09G016100.1 pacid=64781114 polypeptide...,Anaoc.0007s0757.1 pacid=37509413 polypeptide=A...,AgateH1.20G018400.1 pacid=57885542 polypeptide...,AT1G80380.2 pacid=37397400 polypeptide=AT1G803...,Bhyb26.D02G446700.1 pacid=51536579 polypeptide...,BPChr06G16757 pacid=50826782 polypeptide=BPChr...,...,Tylat.11G061800.1 pacid=62722702 polypeptide=T...,Thupl.29381491s0001.1 pacid=44979942 polypepti...,Tp57577_TGAC_v2_mRNA38496 pacid=35956876 polyp...,Vocar.0007s0109.1 pacid=32888163 polypeptide=V...,Vadar_g14814.t1 pacid=52024015 polypeptide=Vad...,VIT_209s0002g05200.2 pacid=38070157 polypeptid...,Yucal.05G018300.1 pacid=61493506 polypeptide=Y...,Zm00001eb156570_T001 pacid=61210747 polypeptid...,Csubellipsoidea33494 pacid=27385793 polypeptid...,Smollendorffii97903 pacid=15414546 polypeptide...

In [6]:
print(f'{len(photo_orthos)} of {len(photo_genes)} photorespiration genes were found.')

13 of 13 photorespiration genes were found.

## Making gene family fastas
We now need to make a fasta containing each gene family across all species. We'll do this by going through each species' fasta a single time, and check whether each sequence belongs to an orthogroup. We'll then append those sequence objects to each gene family to then save out new fastas.

In [13]:
gene_family_lists = defaultdict(list)

base_path = '/mnt/research/Walker_Lab_Research/Serena_project_data/selection-under-heat_data/orthofinder/base_set'
for species in tqdm(listdir(base_path)):
    species_base = splitext(species)[0]
    fasta_sequences = SeqIO.parse(open(f'{base_path}/{species}'),'fasta')
    for fasta in fasta_sequences:
        desc, sequence = fasta.description, str(fasta.seq)
        # Get the orthogroup of this sequence, if any
        if len(photo_orthos[photo_orthos[species_base] == desc]) > 0:
            # Get orthogroup
            orthogroup = photo_orthos[photo_orthos[species_base] == desc]['Orthogroup'].values[0]
            gene_family_lists[orthogroup].append(fasta)

add_path = '/mnt/research/Walker_Lab_Research/Serena_project_data/selection-under-heat_data/orthofinder/add_set'
for species in tqdm(listdir(add_path)):
    species_base = splitext(species)[0]
    fasta_sequences = SeqIO.parse(open(f'{add_path}/{species}'),'fasta')
    for fasta in fasta_sequences:
        desc, sequence = fasta.description, str(fasta.seq)
        # Get the orthogroup of this sequence, if any
        if len(photo_orthos[photo_orthos[species_base] == desc]) > 0:
            orthogroup = photo_orthos[photo_orthos[species_base] == desc]['Orthogroup'].values[0]
            gene_family_lists[orthogroup].append(fasta)

100%|██████████| 64/64 [06:34<00:00,  6.16s/it]
100%|██████████| 147/147 [19:30<00:00,  7.96s/it]

In [19]:
outpath = '/mnt/research/Walker_Lab_Research/Serena_project_data/selection-under-heat_data/orthofinder/gene_family_fastas/'
for orthogroup, seq_list in tqdm(gene_family_lists.items()):
    outfile = f'{outpath}/{orthogroup}_{run_date}.fasta'
    with open(outfile, "w") as output_handle:
        SeqIO.write(seq_list, output_handle, "fasta")

100%|██████████| 12/12 [00:00<00:00, 29.19it/s]